language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: b5pfZjbGwmo8Jr+MuNlrGKe6vVOAuDRxAi2ObTs+l7tPRwXG/F323jozIJEHzNVYUPrmCQIwu/qyDkmaYLY6UPKvbMOQ5yoQSrDO/MsHSCWiNtwbfk3bBe8XWkcQE7gdnewz6ioxyiYZjkyCVccwZdnMpPmMPvKEpfa6uQZW0nSUd00wTx8rqxxSVM0yYcSGKq7xvkEmlStRYY7ogMW0ddzRYY4EoloyuHbugZJph5eJHlvVj+ia4CwWBoF3I5fZq9nN8EduDte3Eqoy61Eocm5FiiLo3jrucOEp6+wetQ82eS2chYIlVbY2qOG2W79Qy34y4V/fBxdxiQzOd6VQBtRu9nsGtyGkEAGeY9gGiVE9mb3BE+rcb9m1zNHCtTC9pgYFqMzjyXqUdbV0CdXDmY+WuQ8lskgGmIVYxSBWyC58mp9DCPZaD7Jt0ahhKeZ6XlRgTzqmQEWmx/3YBiomqqJBJr8BCHXk3SWZGZA56i7DjV+6GGYksJArrurbernOfhrAJhCngmUDv9R32qJhvxt6tOdDARcaIUXWrcEkgy8QQTqFDsMvnbMVencLOYVX0T+/5uBn95CS7oGqHFS8KQlag0U2uwRllKsMbYl3bc+XagoSmOw8GtRYp7rwNHw6B9EcsTsq4eQnCKPExWSL+9DqeLuko3XlgGPdFU/kVJY=
  app: pghbeer
  skip_cleanup: true
  on:
    repo: jgretz/pghbeer
