language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: TdSZUnR+yAeK4cFZpc1XpPiryL57q/s4vw8CZLqun0u61fMCBWPP8Wb59EiSGV6iYeKfc1NXjy+EkBFhyAzfWh99au4HERtphoWMJ3CbucDk4XRXM5pkegb8uF7QZgGqs2WUI65M6xosV+HLY3M788TbWEYHctiwSbU2ZpsGjizyCrIZUQEHQ3pbawqQBkyn7QS1Upekay9ZoV5idjyvxR9xYaPq1QR7znMHNKJ7SwYrxoqVcdHVAlMUyqsc7MSmYTmSXk8DZ/pgpAniaoFcE1hyuRQMxvxadFaFnTEUz7nBjrQ1L9A9GTmdmypAqNttrK+dfAvANj3FOoF6zpTZW5cSUdQu2BFbx+Mn06TWX+LWGslyB3RHp25hV/PScGjsl9ubQehso69Q2JpFagt5UGktJR9jWRSTE7S+cfVTFsTLIxmkFoiYdhlQ0Vtyjd1DIalP4i3AFeP05rMXWs38PWKgrkXaJY4PY6gz/3ivVgaie1Ufo/7on5QVJ7Sqm6FmU+Jw9BJHWiDvmw8dpelFrZ7PxCBRLJMXR3D7+jKPkCKWVKUZdQK8A+gL55Iujc5bUSXqwdusvAriX2MbF0qqlKTWCEcXjk6fnax6A4PV18B77Iy4cgnHoPeF02tSB7HCcPBt+CE9ul0ZaKMUR/Us7og5UkTgixdD2RnNpJsso3M=
  app: pghbeer
  skip_cleanup: true
  on:
    repo: jgretz/pghbeer
