language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: EtzQjZvqp+bLph4Se5oCZET5t2HGluLEf204WQOajTVyRdqO1gkFLD08+xOyuyDY8YAl7oB7YvEjIowZ/eKLb1odDiWq5eMNL9WremETnlpUFXs1kKZkiJ5RsrQCBrMD5FoleIKoR+Pq3PEOJQPGNFyFDECPPGCh8+uppR4qBW75icPVEONEE0EhoJZU8vVPH99vEds0GPQ6ul4iaj4QXU4M4EScQwSt+8XaJe0YMdtPCezlTTDiyQnuxb4tKy0QIKTOl+XQ765fNkV2CGl6t0p/PZxeXhbjSxF/13XhZELH2rDnPx8xNtzS0drQuaqbUJVNP7kCopd86nsg18o5xLE0tKlP1Mwf8s1Qb/vZhHIKRy3WiWyaN/FpAA0rQihBXGhhC/cn+DCD8UsPqtX34UFIZ2UwES6Jt6XQSMzoMlAPfwO0me+eHlv08pieydzdwMug+KdJcvevprBoeqqmdnuA1yxLagT12rj+B6BhRm33wzhij9pEVIIEFQrKXtQPDrHMfUz3Yp07fvsUh8kEqehqi5u1ORuvuerqqcpyVBtnIDDHL5EvQ7TShIfDTTz86hubJh0HCYjWge5GpfTdVunA1mlQ+XAMzB61E8OMIts8CyWpaDmiefJ++GVJ4sFe9pbdI2z1qYfoliC3s4lGGTTyVau/vo30eqtLx8quLUw=
  app: pghbeer
  skip_cleanup: true
  on:
    repo: jgretz/pghbeer
