# fly.toml app configuration file generated for pghbeer on 2023-05-22T15:59:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pghbeer"
primary_region = "bos"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
